DO $$ BEGIN
    CREATE TYPE project_state_enum   AS ENUM ('ACTIVE', 'ARCHIVED', 'COMPLETED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
 
DO $$ BEGIN
    CREATE TYPE project_role_enum    AS ENUM ('OWNER', 'ADMIN', 'MEMBER', 'VIEWER');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
 
DO $$ BEGIN
    CREATE TYPE task_state_enum      AS ENUM ('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
 
DO $$ BEGIN
    CREATE TYPE subtask_state_enum   AS ENUM ('PENDING', 'COMPLETED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "role" (
    "role_id"     INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        VARCHAR(50)  NOT NULL UNIQUE,
    "description" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("role_id")
);

CREATE TABLE IF NOT EXISTS "users" (
    "user_id"       BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"          VARCHAR(100) NOT NULL,
    "lastname"      VARCHAR(100) NOT NULL,
    "email"         VARCHAR(255) NOT NULL UNIQUE,
    "password_hash" TEXT         NOT NULL,
    "state"         BOOLEAN      NOT NULL DEFAULT TRUE,
    "date_created"  TIMESTAMP    NOT NULL DEFAULT NOW(),
    "last_access"   TIMESTAMP    NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("user_id")
);
 

CREATE TABLE IF NOT EXISTS "users_roles" (
    "user_id" BIGINT  NOT NULL,
    "role_id" INTEGER NOT NULL,
    PRIMARY KEY ("user_id", "role_id"),
    CONSTRAINT fk_ur_user FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE,
    CONSTRAINT fk_ur_role FOREIGN KEY ("role_id") REFERENCES "role"  ("role_id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "projects" (
    "project_id"   BIGINT             NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"         VARCHAR(255)       NOT NULL,
    "description"  TEXT               NOT NULL,
    "state"        project_state_enum NOT NULL DEFAULT 'ACTIVE',
    "owner_id"     BIGINT             NOT NULL,
    "date_created" TIMESTAMP          NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("project_id"),
    CONSTRAINT fk_proj_owner FOREIGN KEY ("owner_id") REFERENCES "users" ("user_id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "project_users" (
    "id"           BIGINT            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "project_id"   BIGINT            NOT NULL,
    "user_id"      BIGINT            NOT NULL,
    "project_role" project_role_enum NOT NULL DEFAULT 'MEMBER',
    PRIMARY KEY ("id"),
    UNIQUE ("project_id", "user_id"),
    CONSTRAINT fk_pu_project FOREIGN KEY ("project_id") REFERENCES "projects" ("project_id") ON DELETE CASCADE,
    CONSTRAINT fk_pu_user    FOREIGN KEY ("user_id")    REFERENCES "users"     ("user_id")    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "categories" (
    "category_id" INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        VARCHAR(100) NOT NULL,
    "color"       VARCHAR(7)   NOT NULL,
    "project_id"  BIGINT       NOT NULL,
    PRIMARY KEY ("category_id"),
    CONSTRAINT fk_cat_project FOREIGN KEY ("project_id") REFERENCES "projects" ("project_id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "tags" (
    "tag_id"     BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"       VARCHAR(100) NOT NULL,
    "color"      VARCHAR(7)   NOT NULL,
    "project_id" BIGINT       NOT NULL,
    PRIMARY KEY ("tag_id"),
    CONSTRAINT fk_tag_project FOREIGN KEY ("project_id") REFERENCES "projects" ("project_id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "task" (
    "task_id"      BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title"        VARCHAR(255)    NOT NULL,
    "description"  TEXT            NOT NULL,
    "init_date"    TIMESTAMP       NULL,
    "end_date"     TIMESTAMP       NULL,
    "state"        task_state_enum NOT NULL DEFAULT 'TODO',
    "project_id"   BIGINT          NOT NULL,
    "category_id"  INTEGER         NOT NULL,
    "user_id"      BIGINT          NOT NULL,
    "date_created" TIMESTAMP       NOT NULL DEFAULT NOW(),
    "date_update"  TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("task_id"),
    CONSTRAINT fk_task_project  FOREIGN KEY ("project_id")  REFERENCES "projects"   ("project_id")  ON DELETE CASCADE,
    CONSTRAINT fk_task_category FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id") ON DELETE RESTRICT,
    CONSTRAINT fk_task_user     FOREIGN KEY ("user_id")     REFERENCES "users"       ("user_id")     ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "subtasks" (
    "subtask_id" BIGINT            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "task_id"    BIGINT            NOT NULL,
    "title"      VARCHAR(255)      NOT NULL,
    "state"      subtask_state_enum NOT NULL DEFAULT 'PENDING',
    PRIMARY KEY ("subtask_id"),
    CONSTRAINT fk_sub_task FOREIGN KEY ("task_id") REFERENCES "task" ("task_id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "task_tags" (
    "task_id" BIGINT NOT NULL,
    "tag_id"  BIGINT NOT NULL,
    PRIMARY KEY ("task_id", "tag_id"),
    CONSTRAINT fk_tt_task FOREIGN KEY ("task_id") REFERENCES "task" ("task_id") ON DELETE CASCADE,
    CONSTRAINT fk_tt_tag  FOREIGN KEY ("tag_id")  REFERENCES "tags" ("tag_id")  ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "comments" (
    "comment_id"   BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "content"      TEXT      NOT NULL,
    "task_id"      BIGINT    NOT NULL,
    "user_id"      BIGINT    NOT NULL,
    "date_created" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("comment_id"),
    CONSTRAINT fk_com_task FOREIGN KEY ("task_id") REFERENCES "task"  ("task_id") ON DELETE CASCADE,
    CONSTRAINT fk_com_user FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE RESTRICT
);

INSERT INTO "role" ("name", "description") VALUES
    ('ADMIN', 'Administrador del sistema con acceso total'),
    ('USER',  'Usuario estándar de la plataforma')
ON CONFLICT ("name") DO NOTHING;